YOUTUBE_API_KEY = "AIzaSyC4XJXVvbWcoUJGXs9K-Ph7DnN5KRz3Rp0"
SUPABASE_URL = "https://jfnaqogzmeykmfjcmddo.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmbmFxb2d6bWV5a21mamNtZGRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTQ0NjMsImV4cCI6MjA3Mzc5MDQ2M30.u1os_p7z01MBkkWDf8cRTo6emSyTxetKcRMC6mmTukA"
